import { useCallback, useEffect, useState } from "react";
import { api, type EventDetail, type EventSummary, type Insights, type QueryResult, type Stats, websocketUrl } from "./lib/api";
import "./App.css";

type Page = "Dashboard" | "Objects" | "Screening" | "Risk Analysis" | "Propagation" | "Settings";
const navItems: Page[] = ["Dashboard", "Objects", "Screening", "Risk Analysis", "Propagation"];

function App() {
  const [page, setPage] = useState<Page>("Dashboard");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [stats, setStats] = useState<Stats | null>(null);
  const [events, setEvents] = useState<EventSummary[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [socketState, setSocketState] = useState("connecting");
  const loadDashboard = useCallback(async () => { try { const [nextStats, nextEvents] = await Promise.all([api.stats(), api.events()]); setStats(nextStats); setEvents(nextEvents.items); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Backend unavailable"); } }, []);
  // The initial fetch synchronizes React state with the external FastAPI store.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void loadDashboard(); }, [loadDashboard]);
  useEffect(() => { let socket: WebSocket | undefined; let retry: number | undefined; let stopped = false; const connect = () => { socket = new WebSocket(websocketUrl()); socket.onopen = () => setSocketState("live"); socket.onmessage = (message) => { const event = JSON.parse(message.data) as { type: string }; if (event.type === "refresh_started") setRefreshing(true); if (["refresh_completed", "refresh_failed", "event_created", "event_updated"].includes(event.type)) { setRefreshing(event.type !== "refresh_completed" && event.type !== "refresh_failed"); void loadDashboard(); } }; socket.onclose = () => { setSocketState("offline"); if (!stopped) retry = window.setTimeout(connect, 3000); }; socket.onerror = () => setSocketState("offline"); }; connect(); return () => { stopped = true; if (retry) window.clearTimeout(retry); socket?.close(); }; }, [loadDashboard]);
  const refresh = async () => { setRefreshing(true); try { await api.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Refresh failed"); setRefreshing(false); } };
  const navigate = (item: Page) => { setPage(item); setSidebarOpen(false); };
  return <div className={`app ${sidebarOpen ? "sidebar-open" : ""}`}><button className="mobile-menu-button" onClick={() => setSidebarOpen((open) => !open)} aria-label="Toggle navigation" aria-expanded={sidebarOpen}>☰</button><aside className="sidebar"><div className="brand"><div className="brand-icon">P</div><span>PERIGEE</span></div><nav>{navItems.map((item) => <button key={item} className={`nav-item ${page === item ? "active" : ""}`} onClick={() => navigate(item)}>{item}</button>)}</nav><div className="sidebar-bottom"><button className={`nav-item ${page === "Settings" ? "active" : ""}`} onClick={() => navigate("Settings")}>Settings</button></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">ORBITAL SAFETY SYSTEM</p><h1>Perigee {page}</h1></div><div className={`status ${socketState !== "live" ? "status-muted" : ""}`}><span className="status-dot" />{socketState === "live" ? "Live telemetry" : "Backend reconnecting"}</div></header>{error && <div className="backend-alert" role="alert">Backend connection issue: {error}</div>}{page === "Dashboard" && <Dashboard stats={stats} events={events} refreshing={refreshing} onRefresh={refresh} onSelect={setSelectedId} />}{page === "Objects" && <ObjectsPage stats={stats} />}{page === "Screening" && <ScreeningPage refreshing={refreshing} onRefresh={refresh} />}{page === "Risk Analysis" && <EmptyModule title="Risk analysis follows live conjunction events" />}{page === "Propagation" && <EmptyModule title="Select an object from the live catalog" />}{page === "Settings" && <SettingsPage />}</main>{selectedId && <EventDrawer eventId={selectedId} onClose={() => setSelectedId(null)} />}</div>;
}

function Dashboard({ stats, events, refreshing, onRefresh, onSelect }: { stats: Stats | null; events: EventSummary[]; refreshing: boolean; onRefresh: () => void; onSelect: (id: string) => void }) { return <><section className="stats"><StatCard label="Tracked Objects" value={stats?.objects_tracked} hint={stats?.data_source === "cache" ? "Serving cached catalog" : "Live catalog"} /><StatCard label="Active Conjunctions" value={stats?.events_screened} hint="Deterministic screening results" /><StatCard label="Critical Alerts" value={stats?.critical_count} hint="Requires analyst attention" accent="critical" /><StatCard label="Last Refresh" value={stats?.last_refresh_display ?? "Never"} hint={refreshing ? "Screening in progress" : "Refresh Now is available"} /></section><section className="content-grid"><div className="panel large"><div className="panel-header"><div><p className="eyebrow">ORBITAL OVERVIEW</p><h2>Live screening picture</h2></div><button className="outline-btn" onClick={onRefresh} disabled={refreshing}>{refreshing ? "Screening…" : "Refresh now"}</button></div><OrbitView events={events} /></div><div className="panel"><div className="panel-header"><div><p className="eyebrow">RISK MONITOR</p><h2>Priority events</h2></div></div>{events.length ? <div className="event-list">{events.slice(0, 5).map((event) => <EventRow key={event.id} event={event} onClick={() => onSelect(event.id)} />)}</div> : <EmptyState message="No conjunctions in the current screen" />}</div></section><AgentPanel events={events} onSelect={onSelect} /><section className="panel table-panel"><div className="panel-header"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest screenings</h2></div></div>{events.length ? events.map((event) => <EventRow key={event.id} event={event} onClick={() => onSelect(event.id)} />) : <EmptyTable message="The backend has not recorded a flagged close approach yet." />}</section></>; }

function StatCard({ label, value = "—", hint, accent }: { label: string; value?: number | string; hint: string; accent?: string }) { return <div className={`card ${accent ? `card-${accent}` : ""}`}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>; }
function EventRow({ event, onClick }: { event: EventSummary; onClick: () => void }) { return <button className="event-row" onClick={onClick}><span className={`tier-dot tier-${event.risk_tier}`} /><span className="event-copy"><strong>{event.object_a.name} × {event.object_b.name}</strong><small>{event.summary}</small></span><span className={`tier-label tier-${event.risk_tier}`}>{event.risk_tier}</span><span className="event-score">{event.risk_score.toFixed(0)}</span></button>; }
function OrbitView({ events }: { events: EventSummary[] }) { return <div className="orbit-placeholder"><div className="orbit orbit-1" /><div className="orbit orbit-2" /><div className="orbit orbit-3" /><div className="earth"><div className="earth-glow" /><span>⊕</span></div><div className="orbit-empty">{events.length ? `${events.length} close approach${events.length === 1 ? "" : "es"} in the live screen` : "No flagged close approaches"}</div><div className="orbit-legend"><span>SGP4 propagation · public TLE data</span></div></div>; }
function ObjectsPage({ stats }: { stats: Stats | null }) { return <section className="panel objects-panel"><div className="panel-header"><div><p className="eyebrow">SPACE OBJECT CATALOG</p><h2>Tracked objects</h2></div><span className="data-badge">{stats?.data_source ?? "waiting"}</span></div><div className="object-summary"><StatCard label="Total Objects" value={stats?.objects_tracked} hint="Stored in Postgres" /><StatCard label="Current Source" value={stats?.data_source ?? "—"} hint="CelesTrak or cache" /></div><EmptyState message="Object catalog detail is available by NORAD ID through the backend API." /></section>; }
function ScreeningPage({ refreshing, onRefresh }: { refreshing: boolean; onRefresh: () => void }) { return <section className="panel screening-config"><div className="panel-header"><div><p className="eyebrow">CONJUNCTION SCREENING</p><h2>Run a deterministic refresh</h2></div></div><p className="screening-copy">Perigee fetches current public orbital elements, propagates the tracked set, and stores only explainable close approaches. The request returns immediately while WebSocket status updates arrive here.</p><button className="screening-btn" onClick={onRefresh} disabled={refreshing}>{refreshing ? "Screening in progress…" : "Run refresh now"}</button></section>; }
function AgentPanel({ events, onSelect }: { events: EventSummary[]; onSelect: (id: string) => void }) { const [question, setQuestion] = useState(""); const [result, setResult] = useState<QueryResult | null>(null); const [insights, setInsights] = useState<Insights | null>(null); const [loading, setLoading] = useState(false); const ask = async () => { if (!question.trim()) return; setLoading(true); try { setResult(await api.query(question)); } finally { setLoading(false); } };
 useEffect(() => { void api.insights().then(setInsights).catch(() => undefined); }, []); return <section className="panel agent-panel"><div className="panel-header"><div><p className="eyebrow">AI-ASSISTED · READ ONLY</p><h2>Ask Perigee</h2></div><span className="data-badge">{result?.source ?? "local qwen3.5:9b"}</span></div><div className="agent-query"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void ask(); }} placeholder="Which alerts need attention?" aria-label="Ask Perigee a question" /><button className="outline-btn" onClick={() => void ask()} disabled={loading}>{loading ? "Thinking…" : "Ask"}</button></div>{result && <div className="agent-answer"><strong>{result.answer}</strong>{result.provider_error && <small>Fallback used: {result.provider_error}</small>}{result.referenced_event_ids.map((id) => <button key={id} className="link-btn" onClick={() => onSelect(id)}>Open referenced event</button>)}</div>}{insights?.insights.length ? <div className="insight-list">{insights.insights.map((insight) => <p key={insight.observation}>◈ {insight.observation}</p>)}</div> : events.length === 0 && <small className="muted-copy">AI observations will appear when the deterministic screen records events.</small>}</section>; }
function EventDrawer({ eventId, onClose }: { eventId: string; onClose: () => void }) { const [detail, setDetail] = useState<EventDetail | null>(null); const [explanation, setExplanation] = useState<Awaited<ReturnType<typeof api.explain>> | null>(null); const [recommendation, setRecommendation] = useState<Awaited<ReturnType<typeof api.recommendation>> | null>(null); useEffect(() => { void api.event(eventId).then(setDetail); }, [eventId]); const explain = async () => { setExplanation(await api.explain(eventId)); setRecommendation(await api.recommendation(eventId).catch(() => null)); }; return <div className="drawer-backdrop" onClick={onClose}><aside className="event-drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={onClose} aria-label="Close event detail">×</button>{detail ? <><p className="eyebrow">DETERMINISTIC EVENT DETAIL</p><h2>{detail.object_a.name} × {detail.object_b.name}</h2><div className={`risk-banner tier-${detail.risk_tier}`}>{detail.risk_tier.toUpperCase()} · score {detail.risk_score.toFixed(1)}</div><p>{detail.summary}</p><div className="detail-grid"><div><small>Miss distance</small><strong>{detail.miss_distance_display}</strong></div><div><small>Relative velocity</small><strong>{detail.relative_velocity_display}</strong></div><div><small>Closest approach</small><strong>{detail.tca_display}</strong></div><div><small>Trend</small><strong>{detail.trend_label}</strong></div></div><h3>Why it was flagged</h3>{Object.entries(detail.factor_breakdown).map(([name, factor]) => <div className="factor" key={name}><div><span>{name.replaceAll("_", " ")}</span><b>{factor.contribution.toFixed(1)}</b></div><div className="factor-bar"><i style={{ width: `${Math.min(100, factor.contribution)}%` }} /></div><small>{factor.caption}</small></div>)}<button className="screening-btn" onClick={() => void explain()}>{explanation ? "Refresh AI explanation" : "Explain with local AI"}</button>{explanation && <div className="ai-box"><small>AI-assisted · {explanation.source}</small><strong>{explanation.headline}</strong><p>{explanation.explanation}</p><ul>{explanation.operator_focus.map((focus) => <li key={focus}>{focus}</li>)}</ul><small>{explanation.caveat}</small></div>}{recommendation && <div className="ai-box"><small>AI-assisted triage suggestion</small><p>{recommendation.recommendation}</p></div>}</> : <p>Loading event detail…</p>}</aside></div>; }
function EmptyState({ message }: { message: string }) { return <div className="empty-state"><span>—</span><p>{message}</p><small>Live API data will appear after the next successful screen.</small></div>; }
function EmptyTable({ message }: { message: string }) { return <div className="empty-table"><div className="table-row table-head"><span>OBJECT</span><span>TYPE</span><span>RISK</span><span>STATUS</span><span>UPDATED</span></div><EmptyState message={message} /></div>; }
function EmptyModule({ title }: { title: string }) { return <section className="panel placeholder"><p className="eyebrow">PERIGEE MODULE</p><h2>{title}</h2><EmptyState message="This surface is waiting for a live backend selection." /></section>; }
function SettingsPage() { return <section className="panel"><div className="panel-header"><div><p className="eyebrow">APPLICATION PREFERENCES</p><h2>Preferences</h2></div></div><div className="settings-list"><div className="setting-row"><div><strong>Automatic refresh</strong><small>Backend scheduler runs on its configured interval.</small></div><span className="data-badge">backend controlled</span></div><div className="setting-row"><div><strong>AI assistance</strong><small>Local Ollama output is advisory and visibly labeled.</small></div><span className="data-badge">qwen3.5:9b</span></div></div></section>; }

export default App;
